site_name: 计算科学导论 必修第一册
theme:
  name: material
  language: zh

repo_url: https://github.com/abnerhexu/uc-1
repo_name: abnerhexu/uc-1
copyright: 沙河小分队，蜀ICP备2021028983号-2 (页面由Webhook自动生成)
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js
nav:
  - 序言: 'index.md'
  - 关于课程:
    - 配套实训: 'educoder.md'
    - 本书编写人员: 'team.md'
    - 关于试用版本: 'about.md'
    - 获取Python解释器: 'acquire.md'
  - 语言基础: '1-basis.md'
  - 函数: '2-func.md'
  - 实验：用遗传算法求解旅行商问题: 'exp-ga.md'
  - 科学计算与曲线绘图: '3-scico.md'
  - 实验：Python运行优化: 'exp-opti.md'
  - 输入与文件读取: '4-file.md'
  - 面向对象编程: '5-obj.md'
  - 机器学习与人工智能概论: '6-ai.md'
  - 并行编程入门: '7-para.md'
  - 实验：GPU编程: 'exp-gpu.md'
